### ISSUE TITLE
Gebruik geen ©️ symbool in je code file

### ISSUE THREAD

**Issue by JeroenHeemskerk** [lonne-lee/educom-webshop-basis#12]
Op onderstaande plekken: 
https://github.com/lonne-lee/educom-webshop-basis/blob/cf523892a44eb05ce344a7276529ee1f76250616/index.html#L28
https://github.com/lonne-lee/educom-webshop-basis/blob/cf523892a44eb05ce344a7276529ee1f76250616/about.html#L37
https://github.com/lonne-lee/educom-webshop-basis/blob/cf523892a44eb05ce344a7276529ee1f76250616/contact.html#L143

Gebruik je het uni-code karakter voor copyright, echter niet alle browsers (en vooral de screenreaders voor blinden) kunnen dit soort karakters niet goed verwerken. 

Kijk eens naar [HTML Special Characters](https://www.w3schools.com/html/html_symbols.asp)

**Comment by lonne-lee** [comment]
Vervangen door &copy;
