### ISSUE TITLE
De <footer>element hoort binnen de <body> tag

### ISSUE THREAD

**Issue by JeroenHeemskerk** [lonne-lee/educom-webshop-basis#22]
In HTML horen alle tags (behalve die in `<head>` moeten worden gebruikt) in de `<body>` tag.  
Echter jouw `<footer>` tag staat **na** de `<body>` tag.
https://github.com/lonne-lee/educom-webshop-basis/blob/74924eb41fefb84002eb6244f902240cdb5f4f38/about.html#L36-L40

## `<head>` en `<body>`
Voor de browsers is er een onderscheid tussen `<head>` en `<body>` waarbij in het **head** element allerlei meta data staat over de pagina voor de browser of voor robots, al het andere staat in het **body** element.

## Indeling binnen de body
In HTML5 heb je tags om binnen de `<body>` tag een indeling te maken dit zijn:
* [`<nav>`](https://www.w3schools.com/tags/tag_nav.asp) - voor de navigatie balk
* [`<main>`](https://www.w3schools.com/tags/tag_main.asp) - voor de hoofd content van de pagina
* [`<section>`](https://www.w3schools.com/tags/tag_section.asp) - voor een losse sectie in de pagina of in main 
* [`<article>`](https://www.w3schools.com/tags/tag_article.asp) - voor een los artiekel in de pagina of in main
* [`<aside>`](https://www.w3schools.com/tags/tag_aside.asp) - voor een zijbalk, of een stukje info wat niet met het hoofdverhaal te maken heeft
* [`<footer>`](https://www.w3schools.com/tags/tag_footer.asp) - voor een footer in een sectie/artikel of de hele pagina

**Comment by JeroenHeemskerk** [comment]
Een `<title>` tag in de `<head>` section is ook een goede verbetering

**Comment by frankkruidhofeducom** [comment]
verwarrend is wel dat er naast de `<head>`-tag ook een `<header>`-tag bestaat, dus deze niet door elkaar halen :)
